name: Daily Commit

on:
  schedule:
    - cron: "30 5 * * *" # Runs daily at 5:30 AM UTC
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git (23f3003437@ds.study.iitm.ac.in)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "23f3003437@ds.study.iitm.ac.in"

      - name: Make a change
        run: |
          echo "Last run: $(date)" > last-run.txt
          git add last-run.txt

      - name: Commit and Push
        run: |
          git commit -m "Automated commit: $(date)"
          git push
