name: Daily Commits

on:
  schedule:
    - cron: "30 5 * * *"  # Runs daily at 5:30 AM UTC
  workflow_dispatch:  # Allows manual execution

permissions:
  contents: write

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Git (Email: 23f3003437@ds.study.iitm.ac.in) # ✅ Email in the step name
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "23f3003437@ds.study.iitm.ac.in"

      - name: Make a Change
        run: |
          echo "Last run: $(date)" > last-run.txt
          git add last-run.txt

      - name: Commit and Push (Email: 23f3003437@ds.study.iitm.ac.in) # ✅ Email in step name
        run: |
          git commit -m "Automated commit: $(date)"
          git push
